dist:
  module: github.com/thousandeyes/opentelemetry-collector/cmd/otelcorecol
  name: otelcorecol
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.84.0-dev
  otelcol_version: 0.84.0

receivers:
  - gomod: github.com/thousandeyes/opentelemetry-collector/receiver/otlpreceiver v0.0.0-20230904162551-7a8e3a837a30
exporters:
  - gomod: github.com/thousandeyes/opentelemetry-collector/exporter/loggingexporter v0.0.0-20230904162551-7a8e3a837a30
  - gomod: github.com/thousandeyes/opentelemetry-collector/exporter/otlpexporter v0.0.0-20230904162551-7a8e3a837a30
  - gomod: github.com/thousandeyes/opentelemetry-collector/exporter/otlphttpexporter v0.0.0-20230904162551-7a8e3a837a30
extensions:
  - gomod: github.com/thousandeyes/opentelemetry-collector/extension/ballastextension v0.0.0-20230904162551-7a8e3a837a30
  - gomod: github.com/thousandeyes/opentelemetry-collector/extension/zpagesextension v0.0.0-20230904162551-7a8e3a837a30
processors:
  - gomod: github.com/thousandeyes/opentelemetry-collector/processor/batchprocessor v0.0.0-20230904162551-7a8e3a837a30
  - gomod: github.com/thousandeyes/opentelemetry-collector/processor/memorylimiterprocessor v0.0.0-20230904162551-7a8e3a837a30
connectors:
  - gomod: github.com/thousandeyes/opentelemetry-collector/connector/forwardconnector v0.0.0-20230904162551-7a8e3a837a30

