dist:
  module: github.com/thousandeyes/opentelemetry-collector/cmd/otelcorecol
  name: otelcorecol
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.84.0-dev
  otelcol_version: 0.84.0

receivers:
  - gomod: github.com/thousandeyes/opentelemetry-collector/receiver/otlpreceiver v0.0.0-20230904160414-bb0c230d9653
exporters:
  - gomod: github.com/thousandeyes/opentelemetry-collector/exporter/loggingexporter v0.0.0-20230904160414-bb0c230d9653
  - gomod: github.com/thousandeyes/opentelemetry-collector/exporter/otlpexporter v0.0.0-20230904160414-bb0c230d9653
  - gomod: github.com/thousandeyes/opentelemetry-collector/exporter/otlphttpexporter v0.0.0-20230904160414-bb0c230d9653
extensions:
  - gomod: github.com/thousandeyes/opentelemetry-collector/extension/ballastextension v0.0.0-20230904160414-bb0c230d9653
  - gomod: github.com/thousandeyes/opentelemetry-collector/extension/zpagesextension v0.0.0-20230904160414-bb0c230d9653
processors:
  - gomod: github.com/thousandeyes/opentelemetry-collector/processor/batchprocessor v0.0.0-20230904160414-bb0c230d9653
  - gomod: github.com/thousandeyes/opentelemetry-collector/processor/memorylimiterprocessor v0.0.0-20230904160414-bb0c230d9653
connectors:
  - gomod: github.com/thousandeyes/opentelemetry-collector/connector/forwardconnector v0.0.0-20230904160414-bb0c230d9653

replaces:
  - github.com/thousandeyes/opentelemetry-collector => ../../
  - github.com/thousandeyes/opentelemetry-collector/component => ../../component
  - github.com/thousandeyes/opentelemetry-collector/config/configauth => ../../config/configauth
  - github.com/thousandeyes/opentelemetry-collector/config/configcompression => ../../config/configcompression
  - github.com/thousandeyes/opentelemetry-collector/config/configgrpc => ../../config/configgrpc
  - github.com/thousandeyes/opentelemetry-collector/config/confighttp => ../../config/confighttp
  - github.com/thousandeyes/opentelemetry-collector/config/confignet => ../../config/confignet
  - github.com/thousandeyes/opentelemetry-collector/config/configopaque => ../../config/configopaque
  - github.com/thousandeyes/opentelemetry-collector/config/configtelemetry => ../../config/configtelemetry
  - github.com/thousandeyes/opentelemetry-collector/config/configtls => ../../config/configtls
  - github.com/thousandeyes/opentelemetry-collector/config/internal => ../../config/internal
  - github.com/thousandeyes/opentelemetry-collector/confmap => ../../confmap
  - github.com/thousandeyes/opentelemetry-collector/consumer => ../../consumer
  - github.com/thousandeyes/opentelemetry-collector/connector => ../../connector
  - github.com/thousandeyes/opentelemetry-collector/connector/forwardconnector => ../../connector/forwardconnector
  - github.com/thousandeyes/opentelemetry-collector/exporter => ../../exporter
  - github.com/thousandeyes/opentelemetry-collector/exporter/loggingexporter => ../../exporter/loggingexporter
  - github.com/thousandeyes/opentelemetry-collector/exporter/otlpexporter => ../../exporter/otlpexporter
  - github.com/thousandeyes/opentelemetry-collector/exporter/otlphttpexporter => ../../exporter/otlphttpexporter
  - github.com/thousandeyes/opentelemetry-collector/extension => ../../extension
  - github.com/thousandeyes/opentelemetry-collector/extension/auth => ../../extension/auth
  - github.com/thousandeyes/opentelemetry-collector/extension/ballastextension => ../../extension/ballastextension
  - github.com/thousandeyes/opentelemetry-collector/extension/zpagesextension => ../../extension/zpagesextension
  - github.com/thousandeyes/opentelemetry-collector/featuregate => ../../featuregate
  - github.com/thousandeyes/opentelemetry-collector/pdata => ../../pdata
  - github.com/thousandeyes/opentelemetry-collector/processor => ../../processor
  - github.com/thousandeyes/opentelemetry-collector/receiver => ../../receiver
  - github.com/thousandeyes/opentelemetry-collector/receiver/otlpreceiver => ../../receiver/otlpreceiver
  - github.com/thousandeyes/opentelemetry-collector/processor/batchprocessor => ../../processor/batchprocessor
  - github.com/thousandeyes/opentelemetry-collector/processor/memorylimiterprocessor => ../../processor/memorylimiterprocessor
  - github.com/thousandeyes/opentelemetry-collector/semconv => ../../semconv
