// Code generated by "github.com/thousandeyes/opentelemetry-collector/cmd/builder". DO NOT EDIT.

//go:build !windows
// +build !windows

package main

import "github.com/thousandeyes/opentelemetry-collector/otelcol"

func run(params otelcol.CollectorSettings) error {
	return runInteractive(params)
}
